[database]
path = "./vekta.db"
dimensions = 1280  # in bytes
label_size = 1024  # in bytes
top_k = 5

[search]
method = "exact"  # Can be "exact" or "ann"
ann_num_projections = 10  # Only used if method is "ann"